name: Github Action Workflow
on: [push, pull_request]
jobs:
  job:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:72ebeabcbc037edb3c93703cc9889a3cb4f8aa7d4afb29d4968a361d69f90d84
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.11.1 ocaml-base-compiler.4.11.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    steps:
    - run: cd ~/opam-repository && (git cat-file -e 93abd38ac15a24d900149dc88ebc5329cf0d6196
        || git fetch origin master) && git reset -q --hard 93abd38ac15a24d900149dc88ebc5329cf0d6196
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p "./"
    - run: cd /home/opam 
    - uses: actions/checkout@v2
    - run: opam pin add -yn jekyll-format.dev "./"
    - run: opam depext --update -y jekyll-format.dev $DEPS
    - run: opam install $DEPS
    - run: opam exec -- dune build @install @runtest && rm -rf _build