name: Github OCaml-CI
on: [push, pull_request]
jobs:
  job0:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:d93447965dffd745351c023839441769a9be5c77625b5c322398ca9f1dfb2638
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.10.1 ocaml-base-compiler.4.10.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  job1:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:72ebeabcbc037edb3c93703cc9889a3cb4f8aa7d4afb29d4968a361d69f90d84
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.11.1 ocaml-base-compiler.4.11.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  job2:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:51ba7919ee8c3ab6a9b46569f4555494a4aa57921cfc72ac5f6c3a2ea3b7c00c
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.1.0 astring.0.8.3 base.v0.9.3 base-bigarray.base base-bytes.base
        base-num.base base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0
        cmdliner.1.0.4 conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1
        dune.2.7.1 dune-configurator.2.7.1 ezjsonm.1.1.0 fmt.0.8.6 fpath.0.7.3 hex.1.4.0
        integers.0.4.0 jbuilder.1.0+beta20.2 jsonm.1.0.1 logs.0.7.0 num.0 ocaml.4.03.0
        ocaml-base-compiler.4.03.0 ocaml-compiler-libs.v0.9.0 ocaml-config.1 ocaml-migrate-parsetree.1.7.3
        ocaml-secondary-compiler.4.08.1-1 ocamlbuild.0.14.0 ocamlfind.1.8.1 ocamlfind-secondary.1.8.1
        omd.1.3.1 ppx_ast.v0.9.1 ppx_core.v0.9.0 ppx_derivers.1.2.1 ppx_driver.v0.9.1
        ppx_metaquot.v0.9.0 ppx_optcomp.v0.9.0 ppx_sexp_conv.v0.9.0 ppx_traverse_builtins.v0.9.0
        ppx_type_conv.v0.9.0 ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.0.2.2
        sexplib.v0.9.2 stdio.v0.9.0 stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7
        uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e 3d6ee077dffbb09a2889ee2277e1a0357bf30fd6
        || git fetch origin master) && git reset -q --hard 3d6ee077dffbb09a2889ee2277e1a0357bf30fd6
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  job3:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam:debian-10-ocaml-4.10@sha256:4d2ad4606b9a2e2d57f5a245342dc524b4f769606fc3078c486f002d8474ed4f
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.10.1 ocaml-base-compiler.4.10.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package