name: Github OCaml-CI
on: [push, pull_request]
jobs:
  job0:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:72ebeabcbc037edb3c93703cc9889a3cb4f8aa7d4afb29d4968a361d69f90d84
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.11.1 ocaml-base-compiler.4.11.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  job1:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:d93447965dffd745351c023839441769a9be5c77625b5c322398ca9f1dfb2638
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.10.1 ocaml-base-compiler.4.10.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  job2:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:1ff2b362ab97086663c30b6cb1c4af154c2092c92f340525bff391dce402125f
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.09.1 ocaml-base-compiler.4.09.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  job3:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:f819466b3f075a16199f02882f8cda7198bf21781eba45c2c67b0ea6979ae8ec
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.11.1 ocaml-base-compiler.4.11.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  job4:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:4a7fe8cfbb155725c52da4f1d815001bd89ffd8e483b8c2c321396adc82f673d
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.10.1 ocaml-base-compiler.4.10.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  job5:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:5de16806b699d1de265f018570784eced803d59286fb5d418d3af3f3b27b78f7
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.09.1 ocaml-base-compiler.4.09.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  job6:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:66cb7b9d9943e311f67c3fb324f358164ff7af065f7fd285ad3f0f7a08e16f30
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.11.1 ocaml-base-compiler.4.11.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  job7:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:1c48ed47c17b5fb4fbe7089777bb3dbeab6eb5c217f577d45b56ffac99ff71d5
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.10.1 ocaml-base-compiler.4.10.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  job8:
    runs-on: ubuntu-latest
    container:
      image: ocurrent/opam@sha256:dd753a2049ddee6cfda48b996f2a2dbc23a38122f7f97bbda55237946b0c61ed
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: alcotest.1.2.3 astring.0.8.5 base.v0.14.0 base-bigarray.base base-bytes.base
        base-threads.base base-unix.base bigarray-compat.1.0.0 bos.0.2.0 cmdliner.1.0.4
        conf-m4.1 conf-pkg-config.1.3 csexp.1.3.2 cstruct.6.0.0 ctypes.0.17.1 dune.2.7.1
        dune-configurator.2.7.1 ezjsonm.1.2.0 fmt.0.8.9 fpath.0.7.3 hex.1.4.0 integers.0.4.0
        jsonm.1.0.1 logs.0.7.0 num.1.3 ocaml.4.09.1 ocaml-base-compiler.4.09.1 ocaml-compiler-libs.v0.12.3
        ocaml-config.1 ocaml-migrate-parsetree.2.0.0 ocamlbuild.0.14.0 ocamlfind.1.8.1
        omd.1.3.1 parsexp.v0.14.0 ppx_derivers.1.2.1 ppx_sexp_conv.v0.14.1 ppxlib.0.17.0
        ptime.0.8.5 re.1.9.0 result.1.5 rresult.0.6.0 seq.base sexplib.v0.14.0 sexplib0.v0.14.0
        stdlib-shims.0.1.0 topkg.1.0.3 uchar.0.0.2 uuidm.0.9.7 uutf.1.0.2 yaml.2.1.0
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        || git fetch origin master) && git reset -q --hard ae1dd9a1f8aa445840d9c5e6a05b22cfa86b6e22
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn jekyll-format.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y jekyll-format.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package