name: Github OCaml-CI Check
on: [push, pull_request]
jobs:
  check-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: avsm/setup-ocaml@v1
      - run: git clone https://github.com/$GITHUB_REPOSITORY package && git checkout $GITHUB_SHA
      - run: git clone --recursive https://github.com/patricoferris/ocaml-ci.git 
      - run: cd ocaml-ci && opam install . -y && opam exec -- dune exec ocaml-ci-github --winmac --exit /home/opam/package > /home/opam/package/.github/workflows/ocaml-ci.yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3

