name: Github OCaml-CI Check
on: [push, pull_request]
jobs:
  check-ci:
    runs-on: ubuntu-latest
    container:
      image: patricoferris/ocaml-ci-action:latest
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - run: git clone https://github.com/$GITHUB_REPOSITORY package && cd package && git checkout $GITHUB_SHA
      - name: OCaml-CI 
        run: ocaml-ci-github --winmac --exit /var/lib/ocurrent/package

