name: Github OCaml-CI Check
on: [push, pull_request]
jobs:
  check-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: avsm/setup-ocaml@v1
      - run: git clone https://goithub.com/$GITHUB_REPOSITORY package && git checkout $GITHUB_SHA
      - run: git clone --recursive https://github.com/patricoferris/ocaml-ci.git 
      - run: |
          opam pin add -yn github-workflow git+https://github.com/patricoferris/opam-github-workflow.git#3f05bfaf406511e77595a63f9ba85c0d31a1369a
          opam pin add -yn obuilder-spec "./ocluster/obuilder"
          opam pin add -yn obuilder "./ocluster/obuilder"
          opam pin add -yn current_ansi.dev "./ocurrent"
          opam pin add -yn current_docker.dev "./ocurrent"
          opam pin add -yn current_github.dev "./ocurrent"
          opam pin add -yn current_git.dev "./ocurrent"
          opam pin add -yn current_incr.dev "./ocurrent"
          opam pin add -yn current.dev "./ocurrent"
          opam pin add -yn current_rpc.dev "./ocurrent"
          opam pin add -yn current_slack.dev "./ocurrent"
          opam pin add -yn current_web.dev "./ocurrent"
          opam pin add -yn ocluster-api.dev "./ocluster"
      - run: cd ocaml-ci && opam install --deps-only -y . && opam exec -- dune exec ocaml-ci-github --winmac --exit /home/opam/package > /home/opam/package/.github/workflows/ocaml-ci.yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3

