name: Github OCaml-CI Check
on: [push, pull_request]
jobs:
  check-ci:
    runs-on: ubuntu-latest
    container:
      image: patricoferris/ocaml-ci-action:latest
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - run: git clone https://github.com/$GITHUB_REPOSITORY $GITHUB_WORKSPACE/package && cd $GITHUB_WORKSPACE/package && git checkout $GITHUB_SHA
      - name: OCaml-CI 
        run: ocaml-ci-github --winmac --exit $GITHUB_WORKSPACE/package
      - run: cat $GITHUB_WORKSPACE/package/.github/workflows/ocaml-ci.yml
      - uses: peter-evans/create-pull-request@v3
        with: 
          path: package
          commit-message: OCaml CI
          title: Check OCaml-CI 
          branch: ocaml-ci/check
          base: master


