name: Github OCaml-CI Check
on: [push, pull_request]
jobs:
  check-ci:
    runs-on: ubuntu-latest
    steps:
      - name: OCaml-CI 
        run: docker run -v $(pwd):/var/lib/ocurrent/package -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 -it patricoferris/ocaml-ci-action:latest ocaml-ci-github --winmac --exit /home/opam/package 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3

